version: 2
jobs:
  check:
    working_directory: ~/DangerSample
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - attach_workspace:
          at: ~/DangerSample
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Ktlint
          command: ./gradlew ktlintDebugCheck
      - save_cache:
          paths:
            - ~/DangerSample/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports/ktlint
          destination: reports/
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run danger
          command: bundle exec danger
workflows:
  version: 2
  check:
    jobs:
      - check